name: simple_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0-279.0.dev

dependencies:
  confirm_dialog: ^1.0.3
  flutter:
    sdk: flutter
  http: ^1.2.2
  quickalert: ^1.1.0
  shared_preferences: ^2.3.2
  smooth_page_indicator: ^1.2.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/sliverappbar_header.jpg
    - assets/images/onboarding_1.png
    - assets/images/onboarding_2.png
    - assets/images/onboarding_3.png